POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit",
    "details": "Um evento para quem é apaxionado por programação",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/63da071e-e6c3-4188-80c5-7fafdb21494c/attendees
Content-Type: application/json

{
    "name": "Pedro Henrique Martins Borges",
    "email": "pedroplayborges2@gmail.com"
}


###

GET http://localhost:3333/events/63da071e-e6c3-4188-80c5-7fafdb21494c

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in